pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                dir('HRM') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('HRM') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {

        always {
            echo 'Pipeline Execution Completed'
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}